version: "3"
services:
  nginx:
    container_name: phyrem_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ../phyl.ink:/var/www/html/phyl.ink
      - ../phyrem.com:/var/www/html/phyrem.com
  php:
    container_name: phyrem_php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    #environment:
      #XDEBUG_MODE: debug
      #XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ../phyrem.com:/var/www/html/phyrem.com
      - ../phyl.ink:/var/www/html/phyl.ink
      - ./sessions:/var/cpanel/php/sessions/ea-php70
      - ./logs/php.log:/var/log/fpm-php.www.log
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    container_name: phyrem_mysql
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'phyrem_db'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal
  phpmyadmin:
    container_name: phyrem_phpmyadmin
    image: phpmyadmin
    networks:
      - internal
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=phyrem_mysql
      - PMA_USER=root
networks:
  internal:
    driver: bridge
